import { Inter } from "next/font/google";
import "../globals.css";

//import font
import estedadFont from "@/constant/localFonts";

//import theme
import { ThemeProvider, CssBaseline } from "@mui/material";
import { darkTheme } from "@/theme/Theme";

// import components
import Header from "@/app/(user)/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="en">
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <body
          suppressHydrationWarning={true}
          className={`${estedadFont.variable} font-sans`}
        >
          <Header />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
